@echo off
REM Basic Capacitor setup for Windows - run from project root
echo Installing Capacitor CLI and core...
npm install @capacitor/cli @capacitor/core
echo Initializing Capacitor project (app name: أذكار, id: com.example.azkare)...
npx cap init "أذكار" com.example.azkare --webDir=.
echo Adding Android platform...
npx cap add android
echo Syncing web assets to native projects...
npx cap sync android
echo Setup complete. Open Android Studio with: npx cap open android
pause
